#!/bin/bash
echo "=================================================="
echo "🔍 CHECKING .COM DOMAIN SETUP"
echo "=================================================="
echo ""

echo "1️⃣ Testing .com domain (from internet):"
echo "   URL: https://tpsdhanvantariayurveda.com/"
curl -I -s https://tpsdhanvantariayurveda.com/ | grep -E "HTTP|Server|CF-"
echo ""

echo "2️⃣ Checking if .com goes through Cloudflare:"
CF_CHECK=$(curl -I -s https://tpsdhanvantariayurveda.com/ | grep -i "cloudflare")
if [ ! -z "$CF_CHECK" ]; then
    echo "   ⚠️  .com domain is proxied through Cloudflare"
    echo "   This means it's NOT pointing directly to 88.222.244.84"
    echo "   Cloudflare is serving cached content from somewhere else"
else
    echo "   ✅ Direct connection (not Cloudflare)"
fi
echo ""

echo "3️⃣ Checking .in domain (should be direct to our server):"
echo "   URL: https://tpsdhanvantariayurveda.in/"
curl -I -s https://tpsdhanvantariayurveda.in/ | grep -E "HTTP|Server"
echo ""

echo "=================================================="
echo "📋 DIAGNOSIS"
echo "=================================================="
echo ""
echo "The .com domain is using Cloudflare proxy, which means:"
echo "1. DNS is pointing to Cloudflare, not our server"
echo "2. Cloudflare is caching old content"
echo "3. Our Nginx configuration on the server is NOT being used"
echo ""
echo "SOLUTION OPTIONS:"
echo ""
echo "Option 1: Disable Cloudflare proxy (orange cloud)"
echo "   - Go to Cloudflare dashboard"
echo "   - Find DNS settings for tpsdhanvantariayurveda.com"
echo "   - Click the orange cloud to make it gray (DNS only)"
echo "   - Wait 5 minutes for propagation"
echo ""
echo "Option 2: Purge Cloudflare cache"
echo "   - Go to Cloudflare dashboard"
echo "   - Click 'Caching' → 'Configuration'"
echo "   - Click 'Purge Everything'"
echo "   - Wait 1-2 minutes"
echo ""
echo "Option 3: Update Cloudflare DNS to point to 88.222.244.84"
echo "   - Check current DNS settings"
echo "   - Ensure A record points to: 88.222.244.84"
echo ""
echo "=================================================="
