#!/bin/bash

echo "=================================================="
echo "🔍 ANALYZING CLOUDFLARE DNS CONFIGURATION"
echo "=================================================="
echo ""

echo "Based on your screenshot, I can see:"
echo ""
echo "DNS Records visible:"
echo "  1. CAA records (3x) - DNS only ✅"
echo "  2. CNAME → ayurveda-clinic.pages... - DNS only (with gray icon)"
echo "  3. CNAME www → ayurveda-clinic.pages... - DNS only (with gray icon)"
echo "  4. NS record - DNS only ✅"
echo ""

echo "🎯 CRITICAL ISSUE IDENTIFIED:"
echo "   The CNAME records point to 'ayurveda-clinic.pages...' (Cloudflare Pages)"
echo "   This is NOT pointing to our VPS server at 88.222.244.84"
echo ""

echo "📋 WHAT YOU NEED TO DO:"
echo ""
echo "These CNAME records need to be changed to A records pointing to our server!"
echo ""

echo "Step 1: Delete the existing CNAME records"
echo "   ❌ CNAME: tpsdhanvantariayurveda.com → ayurveda-clinic.pages..."
echo "   ❌ CNAME: www → ayurveda-clinic.pages..."
echo ""

echo "Step 2: Create new A records instead"
echo "   ✅ A: @ (root) → 88.222.244.84 (DNS only - gray cloud)"
echo "   ✅ A: www → 88.222.244.84 (DNS only - gray cloud)"
echo ""

echo "=================================================="
echo "📝 DETAILED INSTRUCTIONS:"
echo "=================================================="
echo ""

echo "1. DELETE CNAME FOR ROOT DOMAIN (@):"
echo "   • Find the CNAME record: tpsdhanvantariayurveda.com → ayurveda-clinic.pages..."
echo "   • Click 'Edit' button (on the right)"
echo "   • Scroll down and click 'Delete' button"
echo "   • Confirm deletion"
echo ""

echo "2. DELETE CNAME FOR WWW:"
echo "   • Find the CNAME record: www → ayurveda-clinic.pages..."
echo "   • Click 'Edit' button (on the right)"
echo "   • Scroll down and click 'Delete' button"
echo "   • Confirm deletion"
echo ""

echo "3. ADD NEW A RECORD FOR ROOT DOMAIN:"
echo "   • Click 'Add record' button"
echo "   • Type: Select 'A'"
echo "   • Name: Type '@' (or leave blank for root)"
echo "   • IPv4 address: Type '88.222.244.84'"
echo "   • Proxy status: Make sure it's GRAY cloud (DNS only)"
echo "   • TTL: Select 'Auto'"
echo "   • Click 'Save'"
echo ""

echo "4. ADD NEW A RECORD FOR WWW:"
echo "   • Click 'Add record' button"
echo "   • Type: Select 'A'"
echo "   • Name: Type 'www'"
echo "   • IPv4 address: Type '88.222.244.84'"
echo "   • Proxy status: Make sure it's GRAY cloud (DNS only)"
echo "   • TTL: Select 'Auto'"
echo "   • Click 'Save'"
echo ""

echo "5. PURGE CACHE (if you haven't already):"
echo "   • Left sidebar: Click 'Caching'"
echo "   • Click 'Configuration'"
echo "   • Find 'Purge Cache' section"
echo "   • Click 'Purge Everything'"
echo "   • Confirm"
echo ""

echo "6. WAIT AND TEST:"
echo "   • Wait 5-10 minutes for DNS propagation"
echo "   • Test: https://tpsdhanvantariayurveda.com/"
echo "   • Press Ctrl+Shift+R to hard refresh"
echo ""

echo "=================================================="
echo "📊 EXPECTED RESULT:"
echo "=================================================="
echo ""
echo "After completing these steps, your DNS should show:"
echo ""
echo "Type    Name    Content          Proxy Status    TTL"
echo "A       @       88.222.244.84    DNS only ⚪     Auto"
echo "A       www     88.222.244.84    DNS only ⚪     Auto"
echo ""
echo "=================================================="
echo ""

echo "🔄 Once you complete this, run this command to verify:"
echo "   ./verify_com_domain.sh"
echo ""

