#!/bin/bash
# ========================================
# MOBILE OPTIMIZATION DEPLOYMENT GUIDE
# TPS DHANVANTARI AYURVEDA v2.5.1
# ========================================

echo "======================================================"
echo "🚀 Mobile Screen Fit Optimization - Deployment Guide"
echo "======================================================"
echo ""
echo "📱 Changes in this update:"
echo "  ✅ Full-width mobile layout (no gaps)"
echo "  ✅ 3-dot menu (⋮) in top-right"
echo "  ✅ Menu slides from right"
echo "  ✅ Compact header (48px height)"
echo "  ✅ Export buttons: 3 columns"
echo "  ✅ Touch-friendly (44px+ buttons)"
echo "  ✅ Optimized padding (12px)"
echo ""
echo "======================================================"
echo "📋 DEPLOYMENT STEPS"
echo "======================================================"
echo ""

echo "Step 1: SSH into your server"
echo "------------------------------"
echo "Command:"
echo "  ssh root@88.222.244.84"
echo ""
echo "Password: Yourkpo@202425"
echo ""
read -p "Press ENTER when connected to server..."

echo ""
echo "Step 2: Navigate to project directory"
echo "--------------------------------------"
echo "Command:"
echo "  cd /var/www/ayurveda"
echo ""
read -p "Press ENTER when done..."

echo ""
echo "Step 3: Pull latest code from GitHub"
echo "------------------------------------"
echo "Command:"
echo "  git pull origin main"
echo ""
echo "Expected output: Already up to date OR files updated"
read -p "Press ENTER when done..."

echo ""
echo "Step 4: Build the project"
echo "-------------------------"
echo "Command:"
echo "  npm run build"
echo ""
echo "This will take ~30 seconds..."
echo "Expected output: dist/_worker.js built successfully"
read -p "Press ENTER when build complete..."

echo ""
echo "Step 5: Restart PM2 service"
echo "---------------------------"
echo "Command:"
echo "  pm2 restart ayurveda-clinic"
echo ""
echo "Expected output: status: online"
read -p "Press ENTER when done..."

echo ""
echo "Step 6: Verify deployment"
echo "-------------------------"
echo "Command:"
echo "  pm2 logs ayurveda-clinic --nostream --lines 10"
echo ""
echo "Expected: No errors, server running on port 3001"
read -p "Press ENTER to continue..."

echo ""
echo "======================================================"
echo "✅ DEPLOYMENT COMPLETE!"
echo "======================================================"
echo ""
echo "🌐 Test URLs:"
echo "  • Production: https://tpsdhanvantariayurveda.in"
echo "  • Direct IP:  http://88.222.244.84:3001"
echo ""
echo "📱 Mobile Testing:"
echo "  1. Open Chrome DevTools (F12)"
echo "  2. Toggle Device Toolbar (Ctrl+Shift+M)"
echo "  3. Select iPhone or Android device"
echo "  4. Clear cache: Ctrl+Shift+R"
echo ""
echo "✅ What to check:"
echo "  [ ] 3-dot menu (⋮) in top-right"
echo "  [ ] No gaps on right side or bottom"
echo "  [ ] Menu slides from right when clicked"
echo "  [ ] Export buttons in 3 columns (CSV, Excel, PDF)"
echo "  [ ] All buttons easy to tap"
echo "  [ ] Content fills screen properly"
echo ""
echo "📞 Login Credentials:"
echo "  Email: Shankaranherbaltreatment@gmail.com"
echo "  Password: 123456"
echo ""
echo "======================================================"
echo "🎉 Enjoy your mobile-optimized clinic app!"
echo "======================================================"
